### PR TITLE
Switch to pnpm-licenses, update to 8.6.1

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #27 #28 #29 #30

Depends on [conda-forge/pnpm-licenses-feedstock#1](https://github.com/conda-forge/pnpm-licenses-feedstock/pull/1)

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
😱 It was green. We could have merged.

**Comment by pavelzw** [comment]
Love the challenge 🤪

**Pull request merged**
